title: Abhishek Tyagi
logo: /assets/img/bio_photo.jpeg
description: A minimalistic place on the interenet to document my journey through life
is_user_page: true
markdown: kramdown
highlighter: rouge
twitter_username: _abhishek42
github_username: abhishek-t-naive
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
