title: Abhishek Tyagi
logo: /assets/img/bio_photo.jpeg
description: 
is_user_page: true
markdown: kramdown
highlighter: rouge
twitter_username: _abhishek42
linkedin_username: in/abhishek-tyagi-a1873596
github_username: abhishek-t-naive
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
